services:
  - type: web
    name: laravel-app
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        value: (copy từ .env)
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sqlX.freesqldatabase.com (thay đúng host)
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: tên database từ freesqldatabase
      - key: DB_USERNAME
        value: tên user từ freesqldatabase
      - key: DB_PASSWORD
        value: mật khẩu user từ freesqldatabase
